// <auto-generated />
using HwProj.ContentService.API.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HwProj.ContentService.API.Migrations
{
    [DbContext(typeof(ContentContext))]
    [Migration("20250511112428_AddFileToCourseUnitTable")]
    partial class AddFileToCourseUnitTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HwProj.ContentService.API.Models.Database.FileRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ExternalKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceCount")
                        .HasColumnType("int");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("FileRecords");
                });

            modelBuilder.Entity("HwProj.ContentService.API.Models.Database.FileToCourseUnit", b =>
                {
                    b.Property<long>("FileRecordId")
                        .HasColumnType("bigint");

                    b.Property<int>("CourseUnitType")
                        .HasColumnType("int");

                    b.Property<long>("CourseUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.HasKey("FileRecordId", "CourseUnitType", "CourseUnitId");

                    b.HasIndex("CourseId");

                    b.HasIndex("FileRecordId");

                    b.ToTable("FileToCourseUnits");
                });

            modelBuilder.Entity("HwProj.ContentService.API.Models.Database.FileToCourseUnit", b =>
                {
                    b.HasOne("HwProj.ContentService.API.Models.Database.FileRecord", "FileRecord")
                        .WithMany()
                        .HasForeignKey("FileRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
