version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    #environment:
      #- RABBITMQ_DEFAULT_USER=guest
      #- RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "2000:5672"
      - "2001:15672"

  hwproj.solutionsservice.api:
    environment:
      - ConnectionStrings:DefaultConnection=Server=mssqllocaldb;Database=SolutionServiceDB;User=sa;Password=Your_password123;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5007
      - EventBus:EventBusHostName=rabbitmq
      - Services:Auth=http://hwproj.authservice.api:5001
      - Services:Courses=http://hwproj.coursesservice.api:5002
    depends_on:
      - rabbitmq
      - hwproj.authservice.api
      - hwproj.coursesservice.api
      - mssqllocaldb
    ports:
      - "5007:5007"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  hwproj.authservice.api:
    environment:
      - ConnectionStrings:DefaultConnection=Server=mssqllocaldb;Database=AuthServiceDB;User=sa;Password=Your_password123;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - EventBus:EventBusHostName=rabbitmq
    depends_on:
      - rabbitmq
      - mssqllocaldb
    ports:
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /root/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  hwproj.apigateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - Services:Auth=http://hwproj.authservice.api:5001
      - Services:Courses=http://hwproj.coursesservice.api:5002
      - Services:Solutions=http://hwproj.solutionsservice.api:5007
      - Services:Notifications=http://hwproj.notificationsservice.api:5006
    depends_on:
      - rabbitmq
      - hwproj.authservice.api
      - hwproj.solutionsservice.api
      - hwproj.coursesservice.api
      - hwproj.notificationsservice.api
    ports:
      - "5000:5000"


  hwproj.coursesservice.api:
    environment:
      - ConnectionStrings:DefaultConnection=Server=mssqllocaldb;Database=CourseWorksServiceDB;MultipleActiveResultSets=True;User=sa;Password=Your_password123;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - EventBus:EventBusHostName=rabbitmq
      - Services:Auth=http://hwproj.authservice.api:5001
    depends_on:
      - rabbitmq
      - hwproj.authservice.api
      - mssqllocaldb
    ports:
      - "5002:5002"


  hwproj.notificationsservice.api:
    environment:
      - ConnectionStrings:DefaultConnection=Server=mssqllocaldb;Database=NotificationsServiceDB;MultipleActiveResultSets=True;User=sa;Password=Your_password123;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5006
      - EventBus:EventBusHostName=rabbitmq
      - Services:Auth=http://hwproj.authservice.api:5001
      - Services:Courses=http://hwproj.coursesservice.api:5002
      - Services:Solutions=http://hwproj.solutionsservice.api:5007
    depends_on:
      - rabbitmq
      - hwproj.authservice.api
      - hwproj.coursesservice.api
      - hwproj.solutionsservice.api
      - mssqllocaldb
    ports:
      - "5006:5006"
  
  mssqllocaldb:
    container_name: mssqllocaldb
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
      - "1488:1433"

  front:
    depends_on:
      - hwproj.apigateway.api
    ports:
      - "3000:3000"