services:
  mssqllocaldb:
    container_name: mssqllocaldb
    environment:
      SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    expose:
      - "${MSSQL_PORT}"
    user: root
    volumes:
      - "${MSSQL_DATA_VOLUME}:/var/opt/mssql/data"
      - "${MSSQL_BACKUPS_VOLUME}:/var/opt/mssql/backups"

  front:
    build:
      context: ./hwproj.front
      dockerfile: ./Dockerfile
      args:
        - VITE_YANDEX_METRICA_ID=${YANDEX_METRICA_ID}

  rabbitmq:
    container_name: rabbitmq
    #environment:
     #- RABBITMQ_DEFAULT_USER=guest
     #- RABBITMQ_DEFAULT_PASS=guest
    expose:
      - "${RABBITMQ_5672_PORT}"
      - "${RABBITMQ_15672_PORT}"

  hwproj.apigateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - Services:Auth=http://hwproj.authservice.api
      - Services:Courses=http://hwproj.coursesservice.api
      - Services:Solutions=http://hwproj.solutionsservice.api
      - Services:Notifications=http://hwproj.notificationsservice.api
      - Services:Content=http://hwproj.contentservice.api
      - EPPlus:ExcelPackage:LicenseContext=NonCommercial
      - GoogleSheets:type=service_account
      - GoogleSheets:project_id=${GOOGLE_SHEETS_PROJECT_ID}
      - GoogleSheets:private_key_id=${GOOGLE_SHEETS_PRIVATE_KEY_ID}
      - GoogleSheets:client_email=${GOOGLE_SHEETS_CLIENT_EMAIL}
      - GoogleSheets:client_id=${GOOGLE_SHEETS_CLIENT_ID}
      - GoogleSheets:auth_uri=https://accounts.google.com/o/oauth2/auth
      - GoogleSheets:token_uri=https://oauth2.googleapis.com/token
      - GoogleSheets:auth_provider_x509_cert_url=https://www.googleapis.com/oauth2/v1/certs
      - GoogleSheets:client_x509_cert_url=${GOOGLE_SHEETS_CLIENT_X509_CERT_URL}
      - GoogleSheets:private_key=${GOOGLE_SHEETS_PRIVATE_KEY}
      - Security:SecurityKey=${AUTH_SERVICE_SECURITY_KEY}
    ports:
      - "127.0.0.1:5000:5000"

  hwproj.authservice.api:
    environment:
      - ConnectionStrings:DefaultConnectionForLinux=Server=mssqllocaldb;Database=AuthServiceDB;User=sa;Password=Your_password123;TrustServerCertificate=true;
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - EventBus:EventBusHostName=rabbitmq
      - AppSettings:SecurityKey=${AUTH_SERVICE_SECURITY_KEY}
      - Github:ClientIdGithub=${GITHUB_CLIENT_ID}
      - Github:ClientSecretGithub=${GITHUB_CLIENT_SECRET}
      - Github:ScopeGitHub=read:user
      - Gtihub:OrganizationNameGithub=${GITHUB_ORGANIZATION_NAME}

  hwproj.coursesservice.api:
    environment:
      - ConnectionStrings:DefaultConnectionForLinux=Server=mssqllocaldb;Database=CourseWorksServiceDB;MultipleActiveResultSets=True;User=sa;Password=Your_password123;
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
      - EventBus:EventBusHostName=rabbitmq
      - Services:Auth=http://hwproj.authservice.api
      - Services:Content=http://hwproj.contentservice.api

  hwproj.notificationsservice.api:
    environment:
      - ConnectionStrings:DefaultConnectionForLinux=Server=mssqllocaldb;Database=NotificationsServiceDB;MultipleActiveResultSets=True;User=sa;Password=Your_password123;TrustServerCertificate=true;
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - EventBus:EventBusHostName=rabbitmq
      - Services:Auth=http://hwproj.authservice.api
      - Services:Courses=http://hwproj.coursesservice.api
      - Services:Solutions=http://hwproj.solutionsservice.api
      - Notification:Mail=${NOTIFICATION_MAIL}
      - Notification:ConnectSite=${NOTIFICATION_CONNECT_SITE}
      - Notification:Password=${NOTIFICATION_PASSWORD}
      - Notification:Url=https://hwproj.ru

  hwproj.solutionsservice.api:
    environment:
      - ConnectionStrings:DefaultConnectionForLinux=Server=mssqllocaldb;Database=SolutionServiceDB;User=sa;Password=Your_password123;
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
      - EventBus:EventBusHostName=rabbitmq
      - Services:Auth=http://hwproj.authservice.api
      - Services:Courses=http://hwproj.coursesservice.api
      - Github:Token=${GITHUB_TOKEN}

  hwproj.contentservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
      - EventBus:EventBusHostName=rabbitmq
      - Services:Auth=http://hwproj.authservice.api
      - ExternalStorageConfiguration:AccessKeyId=${STORAGE_CLIENT_ACCESS_KEY_ID}
      - ExternalStorageConfiguration:SecretKey=${STORAGE_CLIENT_SECRET_KEY}
      - ExternalStorageConfiguration:Region=ru-central1
      - ExternalStorageConfiguration:ServiceURL=https://storage.yandexcloud.net
      - ExternalStorageConfiguration:DefaultBucketName=hwproj-content
      - LocalStorageConfiguration:Path=/app/data/
      - ConnectionStrings:DefaultConnectionForLinux=Server=mssqllocaldb;Database=ContentServiceDB;User=sa;Password=Your_password123;TrustServerCertificate=true;
