version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    
  hwproj.solutionsservice.api:
    image: ${DOCKER_REGISTRY-}hwprojsolutionsserviceapi
    build:
      context: .
      dockerfile: HwProj.SolutionsService/HwProj.SolutionsService.API/Dockerfile


  hwproj.authservice.api:
    image: ${DOCKER_REGISTRY-}hwprojauthserviceapi
    build:
      context: .
      dockerfile: HwProj.AuthService/HwProj.AuthService.API/Dockerfile


  hwproj.apigateway.api:
    image: ${DOCKER_REGISTRY-}hwprojapigatewayapi
    build:
      context: .
      dockerfile: HwProj.APIGateway/HwProj.APIGateway.API/Dockerfile


  hwproj.coursesservice.api:
    image: ${DOCKER_REGISTRY-}hwprojcoursesserviceapi
    build:
      context: .
      dockerfile: HwProj.CoursesService/HwProj.CoursesService.API/Dockerfile


  hwproj.notificationsservice.api:
    image: ${DOCKER_REGISTRY-}hwprojnotificationsserviceapi
    build:
      context: .
      dockerfile: HwProj.NotificationsService/HwProj.NotificationsService.API/Dockerfile
  
  
  mssqllocaldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  
  
  front:
    image: ${DOCKER_REGISTRY-}front
    build:
      context: ./hwproj.front
      dockerfile: ./Dockerfile