name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Knock-knock-knock
        shell: bash
        env:
          KNOCK_HOST: ${{ secrets.SSH_HOST }}
          KNOCK_SEQ: ${{ secrets.KNOCK_SEQ }}
        run: |
          echo "::add-mask::$KNOCK_HOST"
          echo "::add-mask::$KNOCK_SEQ"

          for s in $KNOCK_SEQ; do
            ping -c 1 -s "$s" "$KNOCK_HOST" >/dev/null 2>&1 || true
          done

          sleep 1

      - name: Run script on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            cd /home/${{ secrets.SSH_USER }}/docker/HwProj-2.0.1
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S ./update.sh
